In [2]:
import pandas as pd
pd.set_option("display.max_rows", 500)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [9]:
rod_df = pd.read_excel("rod_prepared_data.xlsx", sheet_name=0)
print(rod_df.shape)
rod_df

(7, 53)

,hotel__name,hotel__brand,etape_rod__0_page_de_connexion__sous_etape_rod__id__data__code_h,etape_rod__0_page_de_connexion__sous_etape_rod__id__data__nom_de_l_hotel,etape_rod__0_page_de_connexion__sous_etape_rod__localisation_geo__data__adresse_postale_1,etape_rod__0_page_de_connexion__sous_etape_rod__localisation_geo__data__adresse_postale_2,etape_rod__0_page_de_connexion__sous_etape_rod__localisation_geo__data__code_postal,etape_rod__0_page_de_connexion__sous_etape_rod__localisation_geo__data__ville,etape_rod__0_page_de_connexion__sous_etape_rod__localisation_geo__data__longitude,etape_rod__0_page_de_connexion__sous_etape_rod__localisation_geo__data__latitude,etape_rod__1_informations_generales__sous_etape_rod__donnees_admin__data__marque,etape_rod__1_informations_generales__sous_etape_rod__donnees_admin__data__nb_de_chambres,etape_rod__1_informations_generales__sous_etape_rod__donnees_admin__data__contrat_type,etape_rod__1_informations_generales__sous_etape_rod__donnees_admin__data__proprietaire,etape_rod__1_informations_generales__sous_etape_rod__donnees_admin__data__dom_dof,etape_rod__1_informations_generales__sous_etape_rod__donnees_admin__data__pms,etape_rod__2_services_equipements__sous_etape_rod__f_b__data__bar,etape_rod__2_services_equipements__sous_etape_rod__f_b__data__restaurant,etape_rod__2_services_equipements__sous_etape_rod__f_b__data__minibar,etape_rod__2_services_equipements__sous_etape_rod__non_f_b__data__salles_de_reunion,etape_rod__2_services_equipements__sous_etape_rod__non_f_b__data__salle_de_sport,etape_rod__2_services_equipements__sous_etape_rod__non_f_b__data__piscine,etape_rod__2_services_equipements__sous_etape_rod__dispo_dans_le_lobby__data__vitrine_refrigeree,etape_rod__2_services_equipements__sous_etape_rod__dispo_dans_le_lobby__data__micro_ondes,etape_rod__2_services_equipements__sous_etape_rod__dispo_dans_le_lobby__data__fontaine_a_eau,etape_rod__2_services_equipements__sous_etape_rod__dispo_dans_le_lobby__data__machine_a_cafe,etape_rod__2_services_equipements__sous_etape_rod__dispo_dans_le_lobby__data__bouilloire,etape_rod__3_profil_de_vos_clients__sous_etape_rod__loisirs__data__top_1_couples,etape_rod__3_profil_de_vos_clients__sous_etape_rod__loisirs__data__top_1_amis,etape_rod__3_profil_de_vos_clients__sous_etape_rod__loisirs__data__top_1_familles,etape_rod__3_profil_de_vos_clients__sous_etape_rod__besoins_de_vos_clients_f_b__data__boissons_alcoolisees,etape_rod__3_profil_de_vos_clients__sous_etape_rod__besoins_de_vos_clients_f_b__data__produits_sales_frais,etape_rod__3_profil_de_vos_clients__sous_etape_rod__besoins_de_vos_clients_f_b__data__produits_sucres_frais,etape_rod__3_profil_de_vos_clients__sous_etape_rod__besoins_de_vos_clients_f_b__data__epicerie_fine,etape_rod__3_profil_de_vos_clients__sous_etape_rod__besoins_de_vos_clients_non_f_b__data__produits_cosmetiques,etape_rod__3_profil_de_vos_clients__sous_etape_rod__besoins_de_vos_clients_non_f_b__data__articles_pour_enfants,etape_rod__3_profil_de_vos_clients__sous_etape_rod__besoins_de_vos_clients_non_f_b__data__pret_a_porter,etape_rod__3_profil_de_vos_clients__sous_etape_rod__besoins_de_vos_clients_non_f_b__data__accessoires,etape_rod__3_profil_de_vos_clients__sous_etape_rod__besoins_de_vos_clients_non_f_b__data__souvenirs,etape_rod__4_informations_corner__sous_etape_rod__corner_de_vente_actuel__data__votre_hotel_dispose_t_il_deja_d_un_corner_de_vente,etape_rod__4_informations_corner__sous_etape_rod__votre_corner_actuel_offre_f_b__data__liste_des_produits_f_b__source_row__85,etape_rod__4_informations_corner__sous_etape_rod__votre_corner_actuel_offre_f_b__data__reception,etape_rod__4_informations_corner__sous_etape_rod__votre_corner_actuel_offre_f_b__data__snacking_comptoir,etape_rod__4_informations_corner__sous_etape_rod__votre_corner_actuel_offre_f_b__data__distributeur_auto,etape_rod__4_informations_corner__sous_etape_rod__votre_corner_actuel_offre_f_b__data__hotel_staff,etape_rod__4_informations_corner__sous_etape_rod__votre_corner_actuel_offre_non_f_b__data__liste_des_produits_non_f_b__source_row__99,etape_rod__4_informations_corner__sous_etape_rod__votre_corner_actuel_offre_non_f_b__data__reception,etape_rod__4_informations_corner__sous_etape_rod__votre_corner_actuel_offre_non_f_b__data__distributeur_auto,etape_rod__4_informations_corner__sous_etape_rod__votre_corner_actuel_offre_non_f_b__data__hotel_staff,etape_rod__4_informations_corner__sous_etape_rod__equipements_disponibles__data__wifi__source_row__122,etape_rod__4_informations_corner__sous_etape_rod__equipements_disponibles__data__internet_filaire_prise_rj45__source_row__123,etape_rod__4_informations_corner__sous_etape_rod__equipements_disponibles__data__alimentation_electrique__source_row__124,etape_rod__4_informations_corner__sous_etape_rod__equipements_disponibles__data__videosurveillance__source_row__125
0,NICE,IBIS BUDGET,H2075,IBIS BUDGET NICE CALIFORNIE,58-60 AVENUE DE LA CALIFORNIE,-,6200,NICE,7.240512,43.689186,IBIS BUDGET,129,FRANCHISE,FAMILLE FARINES,Marion BOROT,FOLS,0,0,0,4,0,0,1,1,1,1,0,0,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,1,0,0,0,1,0,0,0,0,0
1,STRASBOURG,IBIS BUDGET,HB6A3,IBIS BUDGET STRASBOURG REPUBLIQUE,23A RUE OBERLIN,-,67000,STRASBOURG,7.754599,48.591522,IBIS BUDGET,97,FRANCHISE,MILLION - CHOREIN,Christophe RUQUEBOEUCHE,OPERA,0,0,1,0,0,0,0,0,1,1,0,0,1,0,0,1,1,0,0,0,0,0,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1
2,PARIS CDG,IBIS STYLES,H0815,IBIS STYLES ROISSY CDG,2 AVENUE HEINZ GLOOR,-,95700,ROISSY,2.519843,49.006733,IBIS STYLES,309,FRANCHISE,FERRE HOTELS,Sophie CHOLLON,FOLS,1,1,0,1,0,0,0,1,1,1,1,0,0,1,1,1,1,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0
3,MEGEVE,NOVOTEL,HB5I0,NOVOTEL MEGEVE MONT BLANC,1306 ROUTE NATIONALE,LE DOMAINE DE MEZTIVA,74120,MEGEVE,6.619055,45.859165,NOVOTEL,572,FRANCHISE,FAMILLE DELETTRE,Bello DIALLO,FOLS,1,1,0,3,2,1,0,0,0,0,0,0,0,1,1,0,0,1,1,1,1,1,1,0,0,1,0,0,1,1,1,0,1,0,0,0,0
4,TOUR EIFFEL,NOVOTEL,H3546,NOVOTEL PARIS CENTRE TOUR EIFFEL,61 QUAI DE GRENELLE,-,75015,PARIS,2.282836,48.849778,NOVOTEL,764,MANAGÉ,ACCORINVEST FRANCE,Philippe JAUSSELY,OPERA,1,3,0,36,1,1,0,0,1,1,0,0,0,1,0,1,1,1,1,1,1,1,1,1,1,0,0,1,0,0,0,1,0,0,0,0,0
5,MONTMARTRE,MERCURE,H0373,MERCURE MONTMARTRE SACRE COEUR,3 RUE CAULAINCOURT,-,75018,PARIS,2.329923,48.885048,MERCURE,305,MANAGÉ,ACCORINVEST FRANCE,Thibault FREMONT,OPERA,0,1,0,1,1,0,1,0,0,0,0,1,0,0,1,1,1,1,1,1,0,1,1,1,1,1,0,0,1,0,1,0,1,0,0,0,0
6,BOULOGNE,MERCURE,H6188,MERCURE PARIS BOULOGNE,37 PLACE RENÉ CLAIR,-,92100,BOULOGNE-BILLANCOURT,2.256274,48.833827,MERCURE,191,FRANCHISE,GROUPE COVIVIO,Hubert VANQUATHEM,OPERA,1,2,0,13,1,1,1,0,1,0,0,1,0,0,1,1,1,0,0,0,0,1,0,1,1,1,0,0,1,0,1,0,1,0,0,0,0

In [10]:
poi_df = pd.read_excel("poi_prepared_data.xlsx", sheet_name=0)
print(poi_df.shape)
poi_df

(6, 14)

,HOTEL_NAME,HOTEL_CITY,HOTEL_LAT,HOTEL_LON,fb_0_1km,fb_0_2km,fb_0_3km,fb_0_4km,fb_0_5km,not_fb_0_1km,not_fb_0_2km,not_fb_0_3km,not_fb_0_4km,not_fb_0_5km
0,Ibis budget Nice,Nice,43.667571,7.214308,0,0,0,3,3,3,3,6,6,6
1,Ibis budget Strasbourg Centre République,Strasbourg,48.585058,7.736591,0,30,60,102,120,0,3,3,24,36
2,Mercure Paris Montmartre Sacré-Cœur,Paris,48.885240,2.330055,6,12,57,123,195,3,3,27,45,54
3,Novotel Megève Mont-Blanc,Megève,45.859850,6.619478,3,3,6,6,15,0,0,3,3,3
4,Novotel Paris Tour Eiffel,Paris,48.849660,2.283704,3,6,9,36,69,0,9,12,15,18
5,Novotel Porte d’Italie,Paris,48.819054,2.359406,9,18,21,42,75,3,3,3,6,9

In [5]:
weather_df = pd.read_excel("weather_prepared_data.xlsx", sheet_name=0, header=None)
print(weather_df.shape)
weather_df.head(3)

(6, 5117)

        0          1             2             3             4     \
0  HOTEL_LAT  HOTEL_LON  m01_dwpt_max  m01_dwpt_max  m01_dwpt_max
1  43.667571   7.214308          11.7          13.8          10.1
2   45.85985   6.619478           7.8           7.3           2.1

           5             6             7             8             9     \
0  m01_dwpt_max  m01_dwpt_max  m01_dwpt_max  m01_dwpt_max  m01_dwpt_max
1          11.7          13.8          10.1          11.7          13.8
2           7.8           7.3           2.1           7.8           7.3

           10             11             12             13             14    \
0  m01_dwpt_max  m01_dwpt_mean  m01_dwpt_mean  m01_dwpt_mean  m01_dwpt_mean
1          10.1       4.190188        4.94422       2.316801       4.190188
2           2.1      -4.595161      -5.025941      -6.830242      -4.595161

            15             16             17             18             19    \
0  m01_dwpt_mean  m01_dwpt_mean  m01_dwpt_mean  m01_dwpt_mean  m01_dwpt_mean
1        4.94422       2.316801       4.190188        4.94422       2.316801
2      -5.025941      -6.830242      -4.595161      -5.025941      -6.830242

              20               21               22               23    \
0  m01_dwpt_median  m01_dwpt_median  m01_dwpt_median  m01_dwpt_median
1             4.85                6              3.1             4.85
2               -3             -3.4             -4.8               -3

              24               25               26               27    \
0  m01_dwpt_median  m01_dwpt_median  m01_dwpt_median  m01_dwpt_median
1                6              3.1             4.85                6
2             -3.4             -4.8               -3             -3.4

              28            29            30            31            32    \
0  m01_dwpt_median  m01_dwpt_min  m01_dwpt_min  m01_dwpt_min  m01_dwpt_min
1              3.1          -7.7          -7.8         -11.7          -7.7
2             -4.8         -29.7         -23.9         -27.9         -29.7

           33            34            35            36            37    \
0  m01_dwpt_min  m01_dwpt_min  m01_dwpt_min  m01_dwpt_min  m01_dwpt_min
1          -7.8         -11.7          -7.7          -7.8         -11.7
2         -23.9         -27.9         -29.7         -23.9         -27.9

           38            39            40            41            42    \
0  m01_dwpt_q25  m01_dwpt_q25  m01_dwpt_q25  m01_dwpt_q25  m01_dwpt_q25
1           2.1           2.7          -0.9           2.1           2.7
2         -7.65          -9.5       -10.325         -7.65          -9.5

           43            44            45            46            47    \
0  m01_dwpt_q25  m01_dwpt_q25  m01_dwpt_q25  m01_dwpt_q25  m01_dwpt_q75
1          -0.9           2.1           2.7          -0.9           6.9
2       -10.325         -7.65          -9.5       -10.325           0.5

           48            49            50            51            52    \
0  m01_dwpt_q75  m01_dwpt_q75  m01_dwpt_q75  m01_dwpt_q75  m01_dwpt_q75
1             8             6           6.9             8             6
2           0.6            -2           0.5           0.6            -2

           53            54            55         56         57         58    \
0  m01_dwpt_q75  m01_dwpt_q75  m01_dwpt_q75  m01_index  m01_index  m01_index
1           6.9             8             6          5         17         29
2           0.5           0.6            -2         38         50         62

        59         60         61         62         63         64    \
0  m01_index  m01_index  m01_index  m01_index  m01_index  m01_index
1          5         17         29          5         17         29
2         38         50         62         38         50         62

           65            66            67            68            69    \
0  m01_prcp_max  m01_prcp_max  m01_prcp_max  m01_prcp_max  m01_prcp_max
1             8          24.9           5.2             8          24.9
2           4.3           7.9           4.1           4.3           7.9

           70            71            72            73             74    \
0  m01_prcp_max  m01_prcp_max  m01_prcp_max  m01_prcp_max  m01_prcp_mean
1           5.2             8          24.9           5.2       0.091263
2           4.1           4.3           7.9           4.1       0.229435

            75             76             77             78             79    \
0  m01_prcp_mean  m01_prcp_mean  m01_prcp_mean  m01_prcp_mean  m01_prcp_mean
1       0.201344       0.126075       0.091263       0.201344       0.126075
2       0.342339       0.183871       0.229435       0.342339       0.183871

            80             81             82               83    \
0  m01_prcp_mean  m01_prcp_mean  m01_prcp_mean  m01_prcp_median
1       0.091263       0.201344       0.126075                0
2       0.229435       0.342339       0.183871                0

              84               85               86               87    \
0  m01_prcp_median  m01_prcp_median  m01_prcp_median  m01_prcp_median
1                0                0                0                0
2                0                0                0                0

              88               89               90               91    \
0  m01_prcp_median  m01_prcp_median  m01_prcp_median  m01_prcp_median
1                0                0                0                0
2                0                0                0                0

           92            93            94            95            96    \
0  m01_prcp_min  m01_prcp_min  m01_prcp_min  m01_prcp_min  m01_prcp_min
1             0             0             0             0             0
2             0             0             0             0             0

           97            98            99            100           101   \
0  m01_prcp_min  m01_prcp_min  m01_prcp_min  m01_prcp_min  m01_prcp_q25
1             0             0             0             0             0
2             0             0             0             0             0

           102           103           104           105           106   \
0  m01_prcp_q25  m01_prcp_q25  m01_prcp_q25  m01_prcp_q25  m01_prcp_q25
1             0             0             0             0             0
2             0             0             0             0             0

           107           108           109           110           111   \
0  m01_prcp_q25  m01_prcp_q25  m01_prcp_q25  m01_prcp_q75  m01_prcp_q75
1             0             0             0             0             0
2             0             0             0             0           0.2

           112           113           114           115           116   \
0  m01_prcp_q75  m01_prcp_q75  m01_prcp_q75  m01_prcp_q75  m01_prcp_q75
1             0             0             0             0             0
2             0             0           0.2             0             0

           117           118           119           120           121   \
0  m01_prcp_q75  m01_prcp_q75  m01_pres_max  m01_pres_max  m01_pres_max
1             0             0        1035.9        1032.4        1023.4
2           0.2             0        1038.7        1033.7        1026.2

           122           123           124           125           126   \
0  m01_pres_max  m01_pres_max  m01_pres_max  m01_pres_max  m01_pres_max
1        1035.9        1032.4        1023.4        1035.9        1032.4
2        1038.7        1033.7        1026.2        1038.7        1033.7

           127            128            129            130            131   \
0  m01_pres_max  m01_pres_mean  m01_pres_mean  m01_pres_mean  m01_pres_mean
1        1023.4    1018.031317    1017.613306    1007.990323    1018.031317
2        1026.2    1020.037097     1018.51129    1010.418683    1020.037097

            132            133            134            135            136   \
0  m01_pres_mean  m01_pres_mean  m01_pres_mean  m01_pres_mean  m01_pres_mean
1    1017.613306    1007.990323    1018.031317    1017.613306    1007.990323
2     1018.51129    1010.418683    1020.037097     1018.51129    1010.418683

              137              138              139              140   \
0  m01_pres_median  m01_pres_median  m01_pres_median  m01_pres_median
1          1020.05          1017.85             1006          1020.05
2             1020           1018.5           1011.9             1020

              141              142              143              144   \
0  m01_pres_median  m01_pres_median  m01_pres_median  m01_pres_median
1          1017.85             1006          1020.05          1017.85
2           1018.5           1011.9             1020           1018.5

              145           146           147           148           149   \
0  m01_pres_median  m01_pres_min  m01_pres_min  m01_pres_min  m01_pres_min
1             1006         996.1           998           989         996.1
2           1011.9         993.2         999.7         991.5         993.2

           150           151           152           153           154   \
0  m01_pres_min  m01_pres_min  m01_pres_min  m01_pres_min  m01_pres_min
1           998           989         996.1           998           989
2         999.7         991.5         993.2         999.7         991.5

           155           156           157           158           159   \
0  m01_pres_q25  m01_pres_q25  m01_pres_q25  m01_pres_q25  m01_pres_q25
1        1008.2          1013          1000        1008.2          1013
2        1011.7        1013.1        1001.3        1011.7        1013.1

           160           161           162           163           164   \
0  m01_pres_q25  m01_pres_q25  m01_pres_q25  m01_pres_q25  m01_pres_q75
1          1000        1008.2          1013          1000        1028.8
2        1001.3        1011.7        1013.1        1001.3          1030

           165           166           167           168           169   \
0  m01_pres_q75  m01_pres_q75  m01_pres_q75  m01_pres_q75  m01_pres_q75
1          1022          1017        1028.8          1022          1017
2        1024.7        1018.2          1030        1024.7        1018.2

           170           171           172           173           174   \
0  m01_pres_q75  m01_pres_q75  m01_pres_q75  m01_rhum_max  m01_rhum_max
1        1028.8          1022          1017            96           100
2          1030        1024.7        1018.2           100            99

           175           176           177           178           179   \
0  m01_rhum_max  m01_rhum_max  m01_rhum_max  m01_rhum_max  m01_rhum_max
1           100            96           100           100            96
2            97           100            99            97           100

           180           181            182            183            184   \
0  m01_rhum_max  m01_rhum_max  m01_rhum_mean  m01_rhum_mean  m01_rhum_mean
1           100           100      68.086022      69.806452      63.106183
2            99            97      69.505376      70.672043      71.147849

            185            186            187            188            189   \
0  m01_rhum_mean  m01_rhum_mean  m01_rhum_mean  m01_rhum_mean  m01_rhum_mean
1      68.086022      69.806452      63.106183      68.086022      69.806452
2      69.505376      70.672043      71.147849      69.505376      70.672043

            190              191              192              193   \
0  m01_rhum_mean  m01_rhum_median  m01_rhum_median  m01_rhum_median
1      63.106183               69             69.5               62
2      71.147849               84               80               79

              194              195              196              197   \
0  m01_rhum_median  m01_rhum_median  m01_rhum_median  m01_rhum_median
1               69             69.5               62               69
2               84               80               79               84

              198              199           200           201           202   \
0  m01_rhum_median  m01_rhum_median  m01_rhum_min  m01_rhum_min  m01_rhum_min
1             69.5               62            24            28            17
2               80               79             7            16            20

           203           204           205           206           207   \
0  m01_rhum_min  m01_rhum_min  m01_rhum_min  m01_rhum_min  m01_rhum_min
1            24            28            17            24            28
2             7            16            20             7            16

           208           209           210           211           212   \
0  m01_rhum_min  m01_rhum_q25  m01_rhum_q25  m01_rhum_q25  m01_rhum_q25
1            17            61         58.75            53            61
2            20         45.75            54            56         45.75

           213           214           215           216           217   \
0  m01_rhum_q25  m01_rhum_q25  m01_rhum_q25  m01_rhum_q25  m01_rhum_q25
1         58.75            53            61         58.75            53
2            54            56         45.75            54            56

           218           219           220           221           222   \
0  m01_rhum_q75  m01_rhum_q75  m01_rhum_q75  m01_rhum_q75  m01_rhum_q75
1            78            83            76            78            83
2            93            90            87            93            90

           223           224           225           226           227   \
0  m01_rhum_q75  m01_rhum_q75  m01_rhum_q75  m01_rhum_q75  m01_snow_max
1            76            78            83            76             0
2            87            93            90            87           NaN

           228           229           230           231           232   \
0  m01_snow_max  m01_snow_max  m01_snow_max  m01_snow_max  m01_snow_max
1             0             0             0             0             0
2           NaN           NaN           NaN           NaN           NaN

           233           234           235            236            237   \
0  m01_snow_max  m01_snow_max  m01_snow_max  m01_snow_mean  m01_snow_mean
1             0             0             0              0              0
2           NaN           NaN           NaN            NaN            NaN

            238            239            240            241            242   \
0  m01_snow_mean  m01_snow_mean  m01_snow_mean  m01_snow_mean  m01_snow_mean
1              0              0              0              0              0
2            NaN            NaN            NaN            NaN            NaN

            243            244              245              246   \
0  m01_snow_mean  m01_snow_mean  m01_snow_median  m01_snow_median
1              0              0                0                0
2            NaN            NaN              NaN              NaN

              247              248              249              250   \
0  m01_snow_median  m01_snow_median  m01_snow_median  m01_snow_median
1                0                0                0                0
2              NaN              NaN              NaN              NaN

              251              252              253           254   \
0  m01_snow_median  m01_snow_median  m01_snow_median  m01_snow_min
1                0                0                0             0
2              NaN              NaN              NaN           NaN

           255           256           257           258           259   \
0  m01_snow_min  m01_snow_min  m01_snow_min  m01_snow_min  m01_snow_min
1             0             0             0             0             0
2           NaN           NaN           NaN           NaN           NaN

           260           261           262           263           264   \
0  m01_snow_min  m01_snow_min  m01_snow_min  m01_snow_q25  m01_snow_q25
1             0             0             0             0             0
2           NaN           NaN           NaN           NaN           NaN

           265           266           267           268           269   \
0  m01_snow_q25  m01_snow_q25  m01_snow_q25  m01_snow_q25  m01_snow_q25
1             0             0             0             0             0
2           NaN           NaN           NaN           NaN           NaN

           270           271           272           273           274   \
0  m01_snow_q25  m01_snow_q25  m01_snow_q75  m01_snow_q75  m01_snow_q75
1             0             0             0             0             0
2           NaN           NaN           NaN           NaN           NaN

           275           276           277           278           279   \
0  m01_snow_q75  m01_snow_q75  m01_snow_q75  m01_snow_q75  m01_snow_q75
1             0             0             0             0             0
2           NaN           NaN           NaN           NaN           NaN

           280           281           282           283           284   \
0  m01_snow_q75  m01_temp_max  m01_temp_max  m01_temp_max  m01_temp_max
1             0          19.6          18.9            16          19.6
2           NaN          12.3           9.8           8.1          12.3

           285           286           287           288           289   \
0  m01_temp_max  m01_temp_max  m01_temp_max  m01_temp_max  m01_temp_max
1          18.9            16          19.6          18.9            16
2           9.8           8.1          12.3           9.8           8.1

            290            291            292            293            294   \
0  m01_temp_mean  m01_temp_mean  m01_temp_mean  m01_temp_mean  m01_temp_mean
1      10.068145      10.603898       9.454839      10.068145      10.603898
2       1.927823       0.622849      -1.768011       1.927823       0.622849

            295            296            297            298   \
0  m01_temp_mean  m01_temp_mean  m01_temp_mean  m01_temp_mean
1       9.454839      10.068145      10.603898       9.454839
2      -1.768011       1.927823       0.622849      -1.768011

              299              300              301              302   \
0  m01_temp_median  m01_temp_median  m01_temp_median  m01_temp_median
1              9.7             10.9                9              9.7
2              1.4             0.65               -1              1.4

              303              304              305              306   \
0  m01_temp_median  m01_temp_median  m01_temp_median  m01_temp_median
1             10.9                9              9.7             10.9
2             0.65               -1              1.4             0.65

              307           308           309           310           311   \
0  m01_temp_median  m01_temp_min  m01_temp_min  m01_temp_min  m01_temp_min
1                9           3.3             3             2           3.3
2               -1          -9.5          -7.3           -15          -9.5

           312           313           314           315           316   \
0  m01_temp_min  m01_temp_min  m01_temp_min  m01_temp_min  m01_temp_min
1             3             2           3.3             3             2
2          -7.3           -15          -9.5          -7.3           -15

           317           318           319           320           321   \
0  m01_temp_q25  m01_temp_q25  m01_temp_q25  m01_temp_q25  m01_temp_q25
1           8.2             9             7           8.2             9
2          -0.7          -1.9          -4.4          -0.7          -1.9

           322           323           324           325           326   \
0  m01_temp_q25  m01_temp_q25  m01_temp_q25  m01_temp_q25  m01_temp_q75
1             7           8.2             9             7            12
2          -4.4          -0.7          -1.9          -4.4         5.025

           327           328           329           330           331   \

In [14]:
transaction_df = pd.read_excel("transaction_prepared_data.xlsx", sheet_name=0)
print(transaction_df.shape)
transaction_df

(3, 26)

,HOTEL_NAME,HOTEL_CITY,HOTEL_LAT,HOTEL_LON,m02__FB__ALCOOL__montant,m02__FB__ALCOOL__nbr_ventes,m02__FB__FOOD_SALEE__montant,m02__FB__FOOD_SALEE__nbr_ventes,m02__FB__FOOD_SUCREE__montant,m02__FB__FOOD_SUCREE__nbr_ventes,m02__FB__SANS_ALCOOL__montant,m02__FB__SANS_ALCOOL__nbr_ventes,m03__NON_FB__JEUX_ENFANTS__montant,m03__NON_FB__JEUX_ENFANTS__nbr_ventes,m03__NON_FB__SOUVENIRS__montant,m03__NON_FB__SOUVENIRS__nbr_ventes,m08__NON_FB__ACCESSOIRES__montant,m08__NON_FB__ACCESSOIRES__nbr_ventes,m08__NON_FB__COSMETIQUE__montant,m08__NON_FB__COSMETIQUE__nbr_ventes,m08__NON_FB__PAP__montant,m08__NON_FB__PAP__nbr_ventes,m08__NON_FB__SOS__montant,m08__NON_FB__SOS__nbr_ventes,m12__NON_FB__ND__montant,m12__NON_FB__ND__nbr_ventes
0,Ibis budget Nice,Nice,43.667571,7.214308,0,0,0,0,0,0,0,0,0,0,0,0,6,1,10,1,9,1,8,1,0,0
1,Mercure Paris Montmartre Sacré-Cœur,Paris,48.885240,2.330055,18,1,6,1,3,1,20,1,0,0,22,1,0,0,0,0,0,0,0,0,0,0
2,Novotel Megève Mont-Blanc,Megève,45.859850,6.619478,0,0,0,0,0,0,0,0,8,1,0,0,0,0,0,0,0,0,0,0,15,1