In [ ]:
import pandas as pd
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [3]:
df = pd.read_csv("data.csv")
to_drop_cols = [
    "NOM BOUTIQUE",
    "NOM DU PRODUIT",
    "OPERATEUR",
    "MACHINE",
    "ORDER ID (TICKET DE CAISSE)",
    "DATETIME",
    "DATE_HEURE",
    "HOTEL_NAME",
    "HOTEL_LAT",
    "HOTEL_LON",
    "time",
    "lat",
    "lon",
]
df = df.drop(to_drop_cols, axis = 1)
df.fillna(0, inplace = True)
df = pd.get_dummies(df, dtype = int)

In [4]:
df.shape

(82782, 181)

In [5]:
df.head(1)

,QUANTITE,VAT,PRIX TTC,MOIS_D_ANNEE,JOUR_DU_MOIS,JOUR_DE_SEMAINE,JOUR_D_ANNEE,SEMAINE_D_ANNEE,IS_WEEKEND,HEURE_DU_JOUR,ALCOHOL_1_KM,ALCOHOL_2_KM,ALCOHOL_3_KM,BAKERY_1_KM,BAKERY_2_KM,BAKERY_3_KM,CONFECTIONERY_2_KM,CONFECTIONERY_3_KM,CONVENIENCE_1_KM,CONVENIENCE_2_KM,CONVENIENCE_3_KM,COSMETICS_2_KM,COSMETICS_3_KM,GIFT_2_KM,GIFT_3_KM,KIOSK_1_KM,KIOSK_2_KM,KIOSK_3_KM,SUPERMARKET_1_KM,SUPERMARKET_2_KM,SUPERMARKET_3_KM,TOBACCO_1_KM,TOBACCO_2_KM,TOBACCO_3_KM,BEVERAGES_1_KM,BEVERAGES_2_KM,BEVERAGES_3_KM,CONFECTIONERY_1_KM,COSMETICS_1_KM,GIFT_1_KM,GROCERY_2_KM,GROCERY_3_KM,GROCERY_1_KM,ICE_CREAM_2_KM,ICE_CREAM_3_KM,temp,dwpt,rhum,prcp,snow,wdir,wspd,wpgt,pres,tsun,coco,TYPE_0,TYPE_F&B,TYPE_NON-F&B,GAMME_0,GAMME_#REF!,GAMME_ACCESSOIRES,GAMME_ALCOOL,GAMME_COSMETIQUE,GAMME_FOOD SALEE,GAMME_FOOD SUCREE,GAMME_JEUX / ENFANTS,GAMME_PAP,GAMME_SANS ALCOOL,GAMME_SOS,GAMME_SOUVENIRS,MARQUE_0,MARQUE_ -,MARQUE_-,MARQUE_ALAIN MILLIAT,MARQUE_AVRIL,MARQUE_BACCHANTE,MARQUE_BADOIT,MARQUE_BAHIA,MARQUE_BAM&CO,MARQUE_BEENDI,MARQUE_BELVOIR,MARQUE_BLAST SNACK,MARQUE_BOCAUX DU BOCAGE,MARQUE_BOUNTY,MARQUE_BRETS,MARQUE_COCA COLA,MARQUE_COLGATE,MARQUE_CORONA,MARQUE_CRISTALLINE,MARQUE_CRUNCH,MARQUE_DECATHLON,MARQUE_DESPERADOS,MARQUE_DISNEY,MARQUE_DIVERS,MARQUE_DORGEVAL,MARQUE_DORITOS,MARQUE_DUVEL,MARQUE_EAU NEUVE,MARQUE_EVIAN,MARQUE_FANTA,MARQUE_FUZE TEA,MARQUE_GALLIA,MARQUE_GRANINI,MARQUE_GULA,MARQUE_HARIBO,MARQUE_HAUT GIFFRE,MARQUE_HEINEKEN,MARQUE_HUGO LE MARAICHER,MARQUE_IL PAGNOTTO,MARQUE_INNOCENT,MARQUE_KINDER,MARQUE_KINDER BUENO,MARQUE_KIT KAT,MARQUE_KUMQUAT,MARQUE_LA DEBAUCHE,MARQUE_LAYS,MARQUE_LE CHOCOLAT DES FRANÇAIS,MARQUE_LEAMO,MARQUE_LEGO,MARQUE_LION,MARQUE_LIPTON,MARQUE_LOVE & GREEN,MARQUE_M&M'S,MARQUE_M&MS,MARQUE_MARS,MARQUE_MERCURE,MARQUE_MICHEL & AUGUSTIN,MARQUE_MIKADO,MARQUE_MONOPRIX,MARQUE_NEWTREE,MARQUE_NIVEA,MARQUE_NOVOTEL,MARQUE_NUXE,MARQUE_OASIS,MARQUE_ORALB,MARQUE_ORANGINA,MARQUE_PAT PATROUILLE,MARQUE_PERRIER,MARQUE_PLEIN FRUIT,MARQUE_POPPES,MARQUE_PRINGLES,MARQUE_QUI EST CE,MARQUE_RAINS,MARQUE_RED BULL,MARQUE_REDBULL,MARQUE_RESPIRE,MARQUE_RITUALS,MARQUE_RUBIKS CUBE,MARQUE_SAINT MICHEL,MARQUE_SAN PELLEGRINO,MARQUE_SCHWEPPES,MARQUE_SNICKERS,MARQUE_SO CHIPS,MARQUE_SOCHIPS,MARQUE_SODEBO,MARQUE_SPECIAL K,MARQUE_SPRITE,MARQUE_SUPER NATURE,MARQUE_TAO,MARQUE_TOBLERONE,MARQUE_TUC,MARQUE_TWIX,MARQUE_UNO,MARQUE_VITAO,MARQUE_VITTEL,FOURNISSEUR_0,FOURNISSEUR_ -,FOURNISSEUR_-,FOURNISSEUR_ASTORE,FOURNISSEUR_BEENDI,FOURNISSEUR_DECATHLON,FOURNISSEUR_DISNEY,FOURNISSEUR_DIVERS,FOURNISSEUR_MONOPRIX,FOURNISSEUR_OPTIC 2000,FOURNISSEUR_RESPIRE,HOTEL_CITY_Megève,HOTEL_CITY_Nice,HOTEL_CITY_Paris,HOTEL_CITY_Strasbourg
0,1,20.0,6.0,8,10,3,222,32,0,12,1,2,2,2,16,26,1.0,1.0,1,9,20,12.0,12.0,1,1,1.0,3.0,3.0,1.0,7,11,1.0,4.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,18.7,68.0,0.0,0.0,130.0,9.4,17.0,1018.7,55.0,2.0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0

In [23]:
base_cols = [
   # "QUANTITE",
    "PRIX TTC",
    "MOIS_D_ANNEE",

]

neighbor_cols = [col for col in df.columns if col.endswith("_KM")]
meteo_cols = ["temp",	"dwpt",	"rhum",	"prcp",	"snow",	"wdir",	"wspd",	"wpgt",	"pres",	"tsun",	"coco"]
type_cols = ["TYPE_F&B", "TYPE_NON-F&B"]
gamme_cols = ["GAMME_ACCESSOIRES",
 "GAMME_ALCOOL",
 "GAMME_COSMETIQUE",
 "GAMME_FOOD SALEE",
 "GAMME_FOOD SUCREE",
 "GAMME_JEUX / ENFANTS",
 "GAMME_PAP",
 "GAMME_SANS ALCOOL",
 "GAMME_SOS",
 "GAMME_SOUVENIRS"]
city_cols = [col for col in df.columns if col.startswith("HOTEL_CITY_")]

cols = base_cols + neighbor_cols + meteo_cols + type_cols + gamme_cols + city_cols

In [24]:
df1 = df[cols]
df1

,PRIX TTC,MOIS_D_ANNEE,ALCOHOL_1_KM,ALCOHOL_2_KM,ALCOHOL_3_KM,BAKERY_1_KM,BAKERY_2_KM,BAKERY_3_KM,CONFECTIONERY_2_KM,CONFECTIONERY_3_KM,CONVENIENCE_1_KM,CONVENIENCE_2_KM,CONVENIENCE_3_KM,COSMETICS_2_KM,COSMETICS_3_KM,GIFT_2_KM,GIFT_3_KM,KIOSK_1_KM,KIOSK_2_KM,KIOSK_3_KM,SUPERMARKET_1_KM,SUPERMARKET_2_KM,SUPERMARKET_3_KM,TOBACCO_1_KM,TOBACCO_2_KM,TOBACCO_3_KM,BEVERAGES_1_KM,BEVERAGES_2_KM,BEVERAGES_3_KM,CONFECTIONERY_1_KM,COSMETICS_1_KM,GIFT_1_KM,GROCERY_2_KM,GROCERY_3_KM,GROCERY_1_KM,ICE_CREAM_2_KM,ICE_CREAM_3_KM,temp,dwpt,rhum,prcp,snow,wdir,wspd,wpgt,pres,tsun,coco,TYPE_F&B,TYPE_NON-F&B,GAMME_ACCESSOIRES,GAMME_ALCOOL,GAMME_COSMETIQUE,GAMME_FOOD SALEE,GAMME_FOOD SUCREE,GAMME_JEUX / ENFANTS,GAMME_PAP,GAMME_SANS ALCOOL,GAMME_SOS,GAMME_SOUVENIRS,HOTEL_CITY_Megève,HOTEL_CITY_Nice,HOTEL_CITY_Paris,HOTEL_CITY_Strasbourg
0,6.0,8,1,2,2,2,16,26,1.0,1.0,1,9,20,12.0,12.0,1,1,1.0,3.0,3.0,1.0,7,11,1.0,4.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,18.7,68.0,0.0,0.0,130.0,9.4,17.0,1018.7,55.0,2.0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0
1,12.0,8,1,2,2,2,16,26,1.0,1.0,1,9,20,12.0,12.0,1,1,1.0,3.0,3.0,1.0,7,11,1.0,4.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.3,15.8,59.0,0.0,0.0,100.0,1.8,9.0,1018.3,26.0,2.0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0
2,29.0,8,1,2,2,2,16,26,1.0,1.0,1,9,20,12.0,12.0,1,1,1.0,3.0,3.0,1.0,7,11,1.0,4.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26.4,20.9,72.0,0.0,0.0,170.0,11.2,15.0,1021.3,60.0,1.0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0
3,6.0,8,1,2,2,2,16,26,1.0,1.0,1,9,20,12.0,12.0,1,1,1.0,3.0,3.0,1.0,7,11,1.0,4.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28.5,20.5,62.0,0.0,0.0,170.0,9.4,13.0,1020.2,60.0,1.0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0
4,9.0,8,1,2,2,2,16,26,1.0,1.0,1,9,20,12.0,12.0,1,1,1.0,3.0,3.0,1.0,7,11,1.0,4.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26.9,20.2,67.0,0.0,0.0,190.0,9.4,20.4,1018.2,49.0,2.0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82777,24.0,4,13,47,76,46,139,252,12.0,20.0,47,177,316,22.0,44.0,22,43,7.0,31.0,52.0,24.0,68,99,6.0,26.0,43.0,1.0,2.0,4.0,2.0,13.0,6.0,3.0,3.0,1.0,0.0,0.0,18.5,10.1,58.0,0.0,0.0,89.0,10.4,18.5,1022.0,60.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
82778,12.0,4,13,47,76,46,139,252,12.0,20.0,47,177,316,22.0,44.0,22,43,7.0,31.0,52.0,24.0,68,99,6.0,26.0,43.0,1.0,2.0,4.0,2.0,13.0,6.0,3.0,3.0,1.0,0.0,0.0,18.5,10.1,58.0,0.0,0.0,89.0,10.4,18.5,1022.0,60.0,1.0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0
82779,2.9,4,13,47,76,46,139,252,12.0,20.0,47,177,316,22.0,44.0,22,43,7.0,31.0,52.0,24.0,68,99,6.0,26.0,43.0,1.0,2.0,4.0,2.0,13.0,6.0,3.0,3.0,1.0,0.0,0.0,18.5,10.1,58.0,0.0,0.0,89.0,10.4,18.5,1022.0,60.0,1.0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
82780,2.9,4,13,47,76,46,139,252,12.0,20.0,47,177,316,22.0,44.0,22,43,7.0,31.0,52.0,24.0,68,99,6.0,26.0,43.0,1.0,2.0,4.0,2.0,13.0,6.0,3.0,3.0,1.0,0.0,0.0,18.5,10.1,58.0,0.0,0.0,89.0,10.4,18.5,1022.0,60.0,1.0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
82781,6.0,4,13,47,76,46,139,252,12.0,20.0,47,177,316,22.0,44.0,22,43,7.0,31.0,52.0,24.0,68,99,6.0,26.0,43.0,1.0,2.0,4.0,2.0,13.0,6.0,3.0,3.0,1.0,0.0,0.0,18.5,10.1,58.0,0.0,0.0,89.0,10.4,18.5,1022.0,60.0,1.0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0

In [ ]:
df2 = df1.groupby(city_cols + ["MOIS_D_ANNEE"], as_index = False).agg({
    **{col : "mean" for col in  neighbor_cols},
    **{col : ["min", "max", "median", "mean"] for col in meteo_cols},
    **{col : "sum" for col in type_cols + gamme_cols + ["PRIX TTC"]},

})

In [28]:
df2.shape

(48, 64)