In [1]:
import numpy as np
import pandas as pd
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [2]:
import pandas as pd

df = pd.read_csv("data.csv")

df["DATETIME"] = pd.to_datetime(df["DATETIME"])
df["mois"] = df["DATETIME"].dt.month
df["annee"] = df["DATETIME"].dt.year

df["GAMME"] = (
    df["GAMME"]
    .replace("#REF!", "ND")
    .str.replace("JEUX / ENFANTS", "JEUX_ENFANTS", regex=False)
    .fillna("ND")
)

gammes = df["GAMME"].unique()


df_gamme_dummies = pd.get_dummies(df["GAMME"], dtype=int)

df = pd.concat([df, df_gamme_dummies], axis=1)

# Montant de vente
df["montant_vente"] = df["PRIX TTC"] * df["QUANTITE"]

# Infos hôtel à garder
hotel_cols = [
    "HOTEL_NAME",
    "HOTEL_CITY",
    "HOTEL_LAT",
    "HOTEL_LON",
]

train_df = df[df["annee"] < 2026]

# Agrégation par hôtel / mois / type
monthly = (
    train_df
    .groupby(hotel_cols + ["mois", "TYPE", "GAMME"])
    .agg(
        montant=("montant_vente", "sum"),
        nbr_ventes=("ORDER ID (TICKET DE CAISSE)", "nunique"),
        # **{
        #     f"sum_GAMME_{gamme}": (gamme, "sum")
        #     for gamme in df_gamme_dummies
        # }
    )
    .reset_index()
)

# Passage en colonnes
wide = monthly.pivot_table(
    index=hotel_cols,
    columns=["mois", "TYPE", "GAMME"],
    values=["montant", "nbr_ventes"],
    fill_value=0
)

# Aplatir les noms de colonnes
wide.columns = [
    f"m{mois:02d}__{type_}__{gamme_}__{metric}"
    .replace("&", "")
    .replace("-", "_")
    .replace(" ", "_")
    for metric, mois, type_, gamme_ in wide.columns
]

df_hotel_monthly = wide.reset_index()

# Trier les colonnes : infos hôtel puis m01, m02, ...
hotel_cols_final = hotel_cols

monthly_cols = sorted(
    [c for c in df_hotel_monthly.columns if c not in hotel_cols_final],
    key=lambda x: (
        int(x.split("_")[0][1:]),  # mois
        x
    )
)

df_hotel_monthly = df_hotel_monthly[hotel_cols_final + monthly_cols]

In [3]:
df_hotel_monthly.head(10)

,HOTEL_NAME,HOTEL_CITY,HOTEL_LAT,HOTEL_LON,m01__FB__ALCOOL__montant,m01__FB__ALCOOL__nbr_ventes,m01__FB__FOOD_SALEE__montant,m01__FB__FOOD_SALEE__nbr_ventes,m01__FB__FOOD_SUCREE__montant,m01__FB__FOOD_SUCREE__nbr_ventes,m01__FB__SANS_ALCOOL__montant,m01__FB__SANS_ALCOOL__nbr_ventes,m01__FB__SOUVENIRS__montant,m01__FB__SOUVENIRS__nbr_ventes,m01__NON_FB__ACCESSOIRES__montant,m01__NON_FB__ACCESSOIRES__nbr_ventes,m01__NON_FB__COSMETIQUE__montant,m01__NON_FB__COSMETIQUE__nbr_ventes,m01__NON_FB__JEUX_ENFANTS__montant,m01__NON_FB__JEUX_ENFANTS__nbr_ventes,m01__NON_FB__ND__montant,m01__NON_FB__ND__nbr_ventes,m01__NON_FB__PAP__montant,m01__NON_FB__PAP__nbr_ventes,m01__NON_FB__SOS__montant,m01__NON_FB__SOS__nbr_ventes,m01__NON_FB__SOUVENIRS__montant,m01__NON_FB__SOUVENIRS__nbr_ventes,m02__FB__ALCOOL__montant,m02__FB__ALCOOL__nbr_ventes,m02__FB__FOOD_SALEE__montant,m02__FB__FOOD_SALEE__nbr_ventes,m02__FB__FOOD_SUCREE__montant,m02__FB__FOOD_SUCREE__nbr_ventes,m02__FB__SANS_ALCOOL__montant,m02__FB__SANS_ALCOOL__nbr_ventes,m02__FB__SOUVENIRS__montant,m02__FB__SOUVENIRS__nbr_ventes,m02__NON_FB__ACCESSOIRES__montant,m02__NON_FB__ACCESSOIRES__nbr_ventes,m02__NON_FB__COSMETIQUE__montant,m02__NON_FB__COSMETIQUE__nbr_ventes,m02__NON_FB__JEUX_ENFANTS__montant,m02__NON_FB__JEUX_ENFANTS__nbr_ventes,m02__NON_FB__ND__montant,m02__NON_FB__ND__nbr_ventes,m02__NON_FB__PAP__montant,m02__NON_FB__PAP__nbr_ventes,m02__NON_FB__SOS__montant,m02__NON_FB__SOS__nbr_ventes,m02__NON_FB__SOUVENIRS__montant,m02__NON_FB__SOUVENIRS__nbr_ventes,m03__FB__ALCOOL__montant,m03__FB__ALCOOL__nbr_ventes,m03__FB__FOOD_SALEE__montant,m03__FB__FOOD_SALEE__nbr_ventes,m03__FB__FOOD_SUCREE__montant,m03__FB__FOOD_SUCREE__nbr_ventes,m03__FB__SANS_ALCOOL__montant,m03__FB__SANS_ALCOOL__nbr_ventes,m03__FB__SOUVENIRS__montant,m03__FB__SOUVENIRS__nbr_ventes,m03__NON_FB__ACCESSOIRES__montant,m03__NON_FB__ACCESSOIRES__nbr_ventes,m03__NON_FB__COSMETIQUE__montant,m03__NON_FB__COSMETIQUE__nbr_ventes,m03__NON_FB__JEUX_ENFANTS__montant,m03__NON_FB__JEUX_ENFANTS__nbr_ventes,m03__NON_FB__ND__montant,m03__NON_FB__ND__nbr_ventes,m03__NON_FB__PAP__montant,m03__NON_FB__PAP__nbr_ventes,m03__NON_FB__SOS__montant,m03__NON_FB__SOS__nbr_ventes,m03__NON_FB__SOUVENIRS__montant,m03__NON_FB__SOUVENIRS__nbr_ventes,m04__FB__ALCOOL__montant,m04__FB__ALCOOL__nbr_ventes,m04__FB__FOOD_SALEE__montant,m04__FB__FOOD_SALEE__nbr_ventes,m04__FB__FOOD_SUCREE__montant,m04__FB__FOOD_SUCREE__nbr_ventes,m04__FB__SANS_ALCOOL__montant,m04__FB__SANS_ALCOOL__nbr_ventes,m04__FB__SOUVENIRS__montant,m04__FB__SOUVENIRS__nbr_ventes,m04__NON_FB__ACCESSOIRES__montant,m04__NON_FB__ACCESSOIRES__nbr_ventes,m04__NON_FB__COSMETIQUE__montant,m04__NON_FB__COSMETIQUE__nbr_ventes,m04__NON_FB__JEUX_ENFANTS__montant,m04__NON_FB__JEUX_ENFANTS__nbr_ventes,m04__NON_FB__ND__montant,m04__NON_FB__ND__nbr_ventes,m04__NON_FB__PAP__montant,m04__NON_FB__PAP__nbr_ventes,m04__NON_FB__SOS__montant,m04__NON_FB__SOS__nbr_ventes,m04__NON_FB__SOUVENIRS__montant,m04__NON_FB__SOUVENIRS__nbr_ventes,m05__FB__ALCOOL__montant,m05__FB__ALCOOL__nbr_ventes,m05__FB__FOOD_SALEE__montant,m05__FB__FOOD_SALEE__nbr_ventes,m05__FB__FOOD_SUCREE__montant,m05__FB__FOOD_SUCREE__nbr_ventes,m05__FB__SANS_ALCOOL__montant,m05__FB__SANS_ALCOOL__nbr_ventes,m05__FB__SOUVENIRS__montant,m05__FB__SOUVENIRS__nbr_ventes,m05__NON_FB__ACCESSOIRES__montant,m05__NON_FB__ACCESSOIRES__nbr_ventes,m05__NON_FB__COSMETIQUE__montant,m05__NON_FB__COSMETIQUE__nbr_ventes,m05__NON_FB__JEUX_ENFANTS__montant,m05__NON_FB__JEUX_ENFANTS__nbr_ventes,m05__NON_FB__ND__montant,m05__NON_FB__ND__nbr_ventes,m05__NON_FB__PAP__montant,m05__NON_FB__PAP__nbr_ventes,m05__NON_FB__SOS__montant,m05__NON_FB__SOS__nbr_ventes,m05__NON_FB__SOUVENIRS__montant,m05__NON_FB__SOUVENIRS__nbr_ventes,m06__FB__ALCOOL__montant,m06__FB__ALCOOL__nbr_ventes,m06__FB__FOOD_SALEE__montant,m06__FB__FOOD_SALEE__nbr_ventes,m06__FB__FOOD_SUCREE__montant,m06__FB__FOOD_SUCREE__nbr_ventes,m06__FB__SANS_ALCOOL__montant,m06__FB__SANS_ALCOOL__nbr_ventes,m06__FB__SOUVENIRS__montant,m06__FB__SOUVENIRS__nbr_ventes,m06__NON_FB__ACCESSOIRES__montant,m06__NON_FB__ACCESSOIRES__nbr_ventes,m06__NON_FB__COSMETIQUE__montant,m06__NON_FB__COSMETIQUE__nbr_ventes,m06__NON_FB__JEUX_ENFANTS__montant,m06__NON_FB__JEUX_ENFANTS__nbr_ventes,m06__NON_FB__ND__montant,m06__NON_FB__ND__nbr_ventes,m06__NON_FB__PAP__montant,m06__NON_FB__PAP__nbr_ventes,m06__NON_FB__SOS__montant,m06__NON_FB__SOS__nbr_ventes,m06__NON_FB__SOUVENIRS__montant,m06__NON_FB__SOUVENIRS__nbr_ventes,m07__FB__ALCOOL__montant,m07__FB__ALCOOL__nbr_ventes,m07__FB__FOOD_SALEE__montant,m07__FB__FOOD_SALEE__nbr_ventes,m07__FB__FOOD_SUCREE__montant,m07__FB__FOOD_SUCREE__nbr_ventes,m07__FB__SANS_ALCOOL__montant,m07__FB__SANS_ALCOOL__nbr_ventes,m07__FB__SOUVENIRS__montant,m07__FB__SOUVENIRS__nbr_ventes,m07__NON_FB__ACCESSOIRES__montant,m07__NON_FB__ACCESSOIRES__nbr_ventes,m07__NON_FB__COSMETIQUE__montant,m07__NON_FB__COSMETIQUE__nbr_ventes,m07__NON_FB__JEUX_ENFANTS__montant,m07__NON_FB__JEUX_ENFANTS__nbr_ventes,m07__NON_FB__ND__montant,m07__NON_FB__ND__nbr_ventes,m07__NON_FB__PAP__montant,m07__NON_FB__PAP__nbr_ventes,m07__NON_FB__SOS__montant,m07__NON_FB__SOS__nbr_ventes,m07__NON_FB__SOUVENIRS__montant,m07__NON_FB__SOUVENIRS__nbr_ventes,m08__FB__ALCOOL__montant,m08__FB__ALCOOL__nbr_ventes,m08__FB__FOOD_SALEE__montant,m08__FB__FOOD_SALEE__nbr_ventes,m08__FB__FOOD_SUCREE__montant,m08__FB__FOOD_SUCREE__nbr_ventes,m08__FB__SANS_ALCOOL__montant,m08__FB__SANS_ALCOOL__nbr_ventes,m08__FB__SOUVENIRS__montant,m08__FB__SOUVENIRS__nbr_ventes,m08__NON_FB__ACCESSOIRES__montant,m08__NON_FB__ACCESSOIRES__nbr_ventes,m08__NON_FB__COSMETIQUE__montant,m08__NON_FB__COSMETIQUE__nbr_ventes,m08__NON_FB__JEUX_ENFANTS__montant,m08__NON_FB__JEUX_ENFANTS__nbr_ventes,m08__NON_FB__ND__montant,m08__NON_FB__ND__nbr_ventes,m08__NON_FB__PAP__montant,m08__NON_FB__PAP__nbr_ventes,m08__NON_FB__SOS__montant,m08__NON_FB__SOS__nbr_ventes,m08__NON_FB__SOUVENIRS__montant,m08__NON_FB__SOUVENIRS__nbr_ventes,m09__FB__ALCOOL__montant,m09__FB__ALCOOL__nbr_ventes,m09__FB__FOOD_SALEE__montant,m09__FB__FOOD_SALEE__nbr_ventes,m09__FB__FOOD_SUCREE__montant,m09__FB__FOOD_SUCREE__nbr_ventes,m09__FB__SANS_ALCOOL__montant,m09__FB__SANS_ALCOOL__nbr_ventes,m09__FB__SOUVENIRS__montant,m09__FB__SOUVENIRS__nbr_ventes,m09__NON_FB__ACCESSOIRES__montant,m09__NON_FB__ACCESSOIRES__nbr_ventes,m09__NON_FB__COSMETIQUE__montant,m09__NON_FB__COSMETIQUE__nbr_ventes,m09__NON_FB__JEUX_ENFANTS__montant,m09__NON_FB__JEUX_ENFANTS__nbr_ventes,m09__NON_FB__ND__montant,m09__NON_FB__ND__nbr_ventes,m09__NON_FB__PAP__montant,m09__NON_FB__PAP__nbr_ventes,m09__NON_FB__SOS__montant,m09__NON_FB__SOS__nbr_ventes,m09__NON_FB__SOUVENIRS__montant,m09__NON_FB__SOUVENIRS__nbr_ventes,m10__FB__ALCOOL__montant,m10__FB__ALCOOL__nbr_ventes,m10__FB__FOOD_SALEE__montant,m10__FB__FOOD_SALEE__nbr_ventes,m10__FB__FOOD_SUCREE__montant,m10__FB__FOOD_SUCREE__nbr_ventes,m10__FB__SANS_ALCOOL__montant,m10__FB__SANS_ALCOOL__nbr_ventes,m10__NON_FB__ACCESSOIRES__montant,m10__NON_FB__ACCESSOIRES__nbr_ventes,m10__NON_FB__COSMETIQUE__montant,m10__NON_FB__COSMETIQUE__nbr_ventes,m10__NON_FB__JEUX_ENFANTS__montant,m10__NON_FB__JEUX_ENFANTS__nbr_ventes,m10__NON_FB__ND__montant,m10__NON_FB__ND__nbr_ventes,m10__NON_FB__PAP__montant,m10__NON_FB__PAP__nbr_ventes,m10__NON_FB__SOS__montant,m10__NON_FB__SOS__nbr_ventes,m10__NON_FB__SOUVENIRS__montant,m10__NON_FB__SOUVENIRS__nbr_ventes,m11__FB__ALCOOL__montant,m11__FB__ALCOOL__nbr_ventes,m11__FB__FOOD_SALEE__montant,m11__FB__FOOD_SALEE__nbr_ventes,m11__FB__FOOD_SUCREE__montant,m11__FB__FOOD_SUCREE__nbr_ventes,m11__FB__SANS_ALCOOL__montant,m11__FB__SANS_ALCOOL__nbr_ventes,m11__FB__SOUVENIRS__montant,m11__FB__SOUVENIRS__nbr_ventes,m11__NON_FB__ACCESSOIRES__montant,m11__NON_FB__ACCESSOIRES__nbr_ventes,m11__NON_FB__COSMETIQUE__montant,m11__NON_FB__COSMETIQUE__nbr_ventes,m11__NON_FB__JEUX_ENFANTS__montant,m11__NON_FB__JEUX_ENFANTS__nbr_ventes,m11__NON_FB__ND__montant,m11__NON_FB__ND__nbr_ventes,m11__NON_FB__PAP__montant,m11__NON_FB__PAP__nbr_ventes,m11__NON_FB__SOS__montant,m11__NON_FB__SOS__nbr_ventes,m11__NON_FB__SOUVENIRS__montant,m11__NON_FB__SOUVENIRS__nbr_ventes,m12__FB__ALCOOL__montant,m12__FB__ALCOOL__nbr_ventes,m12__FB__FOOD_SALEE__montant,m12__FB__FOOD_SALEE__nbr_ventes,m12__FB__FOOD_SUCREE__montant,m12__FB__FOOD_SUCREE__nbr_ventes,m12__FB__SANS_ALCOOL__montant,m12__FB__SANS_ALCOOL__nbr_ventes,m12__FB__SOUVENIRS__montant,m12__FB__SOUVENIRS__nbr_ventes,m12__NON_FB__ACCESSOIRES__montant,m12__NON_FB__ACCESSOIRES__nbr_ventes,m12__NON_FB__COSMETIQUE__montant,m12__NON_FB__COSMETIQUE__nbr_ventes,m12__NON_FB__JEUX_ENFANTS__montant,m12__NON_FB__JEUX_ENFANTS__nbr_ventes,m12__NON_FB__ND__montant,m12__NON_FB__ND__nbr_ventes,m12__NON_FB__PAP__montant,m12__NON_FB__PAP__nbr_ventes,m12__NON_FB__SOS__montant,m12__NON_FB__SOS__nbr_ventes,m12__NON_FB__SOUVENIRS__montant,m12__NON_FB__SOUVENIRS__nbr_ventes
0,Ibis budget Nice,Nice,43.667571,7.214308,0.0,0.0,28.5,10.0,25.0,12.0,258.1,78.0,0.0,0.0,20.0,2.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,14.0,1.0,0.0,0.0,0.0,0.0,20.0,6.0,17.5,8.0,214.8,65.0,0.0,0.0,10.0,1.0,0.0,0.0,0.00,0.0,0.0,0.0,6.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,19.5,7.0,41.0,18.0,515.4,169.0,0.0,0.0,41.0,4.0,0.0,0.0,0.00,0.0,11.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,55.5,15.0,39.6,16.0,498.1,158.0,0.0,0.0,251.1,17.0,29.0,3.0,0.00,0.0,12.0,1.0,44.0,3.0,22.0,2.0,0.0,0.0,0.0,0.0,70.5,14.0,0.0,0.0,904.8,253.0,0.0,0.0,304.0,25.0,0.0,0.0,18.0,1.0,167.0,13.0,136.0,12.0,14.0,1.0,0.0,0.0,0.0,0.0,113.5,37.0,0.0,0.0,1346.6,384.0,0.0,0.0,428.1,47.0,10.0,1.0,54.00,3.0,295.0,19.0,192.0,17.0,24.0,2.0,0.0,0.0,0.0,0.0,180.0,55.0,0.0,0.0,1481.20,410.0,0.0,0.0,390.5,41.0,20.0,2.0,90.0,5.0,425.0,26.0,148.0,14.0,8.0,1.0,0.0,0.0,0.0,0.0,130.0,32.0,0.0,0.0,1632.8,438.0,0.0,0.0,1095.0,79.0,39.0,4.0,90.0,5.0,352.00,28.0,94.0,9.0,8.0,1.0,0.0,0.0,0.0,0.0,131.0,44.0,47.5,21.0,1190.3,341.0,0.0,0.0,569.0,55.0,40.0,4.0,0.0,0.0,424.0,31.0,190.0,19.0,8.0,1.0,0.0,0.0,0.0,0.0,122.0,40.0,40.0,14.0,940.3,271.0,414.0,38.0,0.0,0.0,0.0,0.0,116.00,10.0,110.0,12.0,56.0,3.0,0.0,0.0,0.0,0.0,59.0,19.0,20.5,13.0,592.8,177.0,0.0,0.0,24.0,4.0,0.0,0.0,0.00,0.0,84.0,7.0,15.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,37.0,13.0,26.5,9.0,506.4,142.0,0.0,0.0,37.0,4.0,0.0,0.0,0.0,0.0,32.0,3.0,16.0,1.0,4.0,1.0,0.0,0.0
1,Ibis budget Strasbourg Centre République,Strasbourg,48.585058,7.736591,0.0,0.0,80.0,17.0,126.0,40.0,417.0,108.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,85.0,16.0,193.5,28.0,466.5,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,152.0,18.0,312.5,64.0,435.5,120.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,202.5,22.0,231.0,50.0,644.5,149.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45.0,11.0,123.0,31.0,486.0,124.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,163.5,33.0,235.5,74.0,1310.0,251.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,210.5,28.0,297.0,62.0,893.00,191.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,205.5,34.0,222.5,61.0,1295.5,291.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80.0,14.0,127.5,39.0,428.5,124.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,207.5,37.0,336.5,78.0,997.5,239.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,450.0,57.0,556.0,136.0,1111.5,275.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,277.5,66.0,712.0,173.0,2374.5,502.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Mercure Paris Montmartre Sacré-Cœur,Paris,48.885240,2.330055,1269.0,62.0,274.0,46.0,621.0,71.0,2630.0,220.0,29.0,2.0,0.0,0.0,72.5,7.0,0.00,0.0,0.0,0.0,0.0,0.0,38.0,3.0,0.0,0.0,1718.0,85.0,552.0,86.0,441.0,93.0,3561.5,389.0,29.0,2.0,0.0,0.0,350.0,9.0,0.00,0.0,0.0,0.0,0.0,0.0,141.0,8.0,210.0,2.0,1765.0,120.0,519.0,77.0,764.0,154.0,4935.0,542.0,14.0,1.0,0.0,0.0,238.0,11.0,0.00,0.0,0.0,0.0,0.0,0.0,182.0,10.0,44.0,2.0,2895.0,160.0,448.0,92.0,763.0,127.0,4983.0,536.0,168.0,4.0,0.0,0.0,404.0,15.0,0.00,0.0,0.0,0.0,0.0,0.0,96.0,6.0,224.0,4.0,2055.0,111.0,543.0,84.0,529.0,106.0,4435.0,397.0,0.0,0.0,0.0,0.0,199.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,124.0,10.0,32.0,1.0,1135.0,76.0,486.0,83.0,783.0,171.0,6244.0,590.0,45.0,3.0,0.0,0.0,266.0,8.0,0.00,0.0,0.0,0.0,0.0,0.0,98.0,4.0,42.0,1.0,1569.0,88.0,588.0,76.0,713.0,136.0,3540.00,341.0,15.0,1.0,0.0,0.0,55.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,34.0,3.0,66.0,3.0,1646.0,90.0,428.0,70.0,753.0,110.0,3853.0,278.0,0.0,0.0,0.0,0.0,12.0,1.0,0.0,0.0,0.00,0.0,0.0,0.0,76.0,5.0,84.0,2.0,3681.0,180.0,798.0,131.0,990.0,160.0,5911.0,522.0,0.0,0.0,0.0,0.0,30.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,42.0,4.0,84.0,2.0,4091.0,196.0,894.0,131.0,818.0,141.0,7595.0,648.0,0.0,0.0,70.7,4.0,0.0,0.0,0.00,0.0,0.0,0.0,110.8,6.0,5.0,1.0,2450.0,118.0,741.0,88.0,770.0,136.0,4705.0,419.0,15.0,1.0,0.0,0.0,80.7,7.0,0.00,0.0,0.0,0.0,0.0,0.0,65.8,5.0,0.0,0.0,2821.0,116.0,558.0,91.0,809.0,106.0,4305.0,414.0,0.0,0.0,0.0,0.0,228.4,17.0,0.0,0.0,0.0,0.0,0.0,0.0,62.9,5.0,22.0,1.0
3,Novotel Megève Mont-Blanc,Megève,45.859850,6.619478,16.0,1.0,78.0,6.0,544.9,41.0,108.0,27.0,16.5,1.0,183.0,8.0,0.0,0.0,248.05,12.0,120.0,6.0,591.0,22.0,112.0,6.0,1.5,2.0,40.0,2.0,79.7,10.0,385.8,65.0,204.0,45.0,0.0,0.0,372.0,16.0,51.9,6.0,349.25,25.0,33.0,3.0,340.0,11.0,545.5,27.0,7.5,6.0,0.0,0.0,152.0,15.0,289.5,51.0,94.5,22.0,0.0,0.0,213.0,9.0,137.0,9.0,486.75,36.0,60.0,5.0,480.0,13.0,89.0,10.0,23.0,6.0,0.0,0.0,63.0,11.0,290.0,30.0,62.0,19.0,0.0,0.0,302.0,12.0,279.5,13.0,250.15,18.0,33.0,3.0,105.0,3.0,123.0,7.0,130.0,4.0,60.0,4.0,75.0,11.0,210.4,25.0,114.0,32.0,14.0,1.0,415.0,11.0,476.8,16.0,198.4,13.0,60.0,4.0,205.0,5.0,116.0,5.0,32.0,1.0,112.0,7.0,114.0,17.0,312.5,33.0,120.0,33.0,7.0,1.0,421.0,14.0,269.8,13.0,318.05,20.0,196.5,13.0,100.0,3.0,180.0,12.0,6.5,3.0,52.0,4.0,192.5,37.0,513.0,76.0,250.00,65.0,6.0,1.0,387.0,13.0,263.9,17.0,320.7,20.0,354.5,22.0,309.0,9.0,376.0,25.0,112.0,3.0,32.0,3.0,229.7,39.0,595.6,80.0,338.5,84.0,36.7,3.0,514.0,17.0,122.4,10.0,615.1,42.0,917.95,50.0,637.0,20.0,535.0,39.0,70.0,4.0,52.0,4.0,61.0,12.0,213.3,33.0,163.0,41.0,33.0,2.0,788.0,16.0,221.6,15.0,230.8,18.0,389.5,25.0,302.0,8.0,236.0,18.0,86.0,6.0,140.0,11.0,78.0,8.0,148.8,16.0,75.0,20.0,240.0,5.0,163.4,9.0,110.2,8.0,71.95,5.0,70.0,3.0,55.0,4.0,96.0,6.0,16.0,2.0,117.3,22.0,205.6,19.0,99.0,24.0,0.0,0.0,797.0,16.0,276.9,11.0,119.85,9.0,139.0,13.0,225.0,6.0,335.0,28.0,21.0,5.0,8.0,1.0,162.0,33.0,792.3,126.0,312.5,88.0,133.0,6.0,535.0,17.0,129.4,12.0,403.9,28.0,195.0,19.0,660.0,21.0,456.0,31.0,101.0,7.0
4,Novotel Paris Tour Eiffel,Paris,48.849660,2.283704,0.0,0.0,2835.1,311.0,1712.8,286.0,3864.5,608.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,2419.0,238.0,0.0,0.0,0.0,0.0,2883.1,309.0,1810.0,294.0,4201.3,649.0,0.0,0.0,0.0,0.0,24.0,3.0,0.00,0.0,0.0,0.0,0.0,0.0,3432.0,351.0,0.0,0.0,0.0,0.0,3580.5,342.0,2105.3,342.0,4495.8,748.0,0.0,0.0,0.0,0.0,48.0,5.0,0.00,0.0,0.0,0.0,0.0,0.0,3052.0,344.0,0.0,0.0,0.0,0.0,4798.5,457.0,2277.1,370.0,5319.3,916.0,0.0,0.0,0.0,0.0,16.0,2.0,0.00,0.0,0.0,0.0,0.0,0.0,2322.0,256.0,0.0,0.0,0.0,0.0,4658.0,487.0,2031.7,359.0,5888.8,971.0,0.0,0.0,0.0,0.0,48.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,2648.0,280.0,0.0,0.0,0.0,0.0,5002.9,559.0,2407.5,381.0,9538.6,1194.0,0.0,0.0,0.0,0.0,24.0,3.0,0.00,0.0,0.0,0.0,0.0,0.0,3962.0,355.0,0.0,0.0,0.0,0.0,6773.5,657.0,3154.5,461.0,11696.67,1442.0,0.0,0.0,0.0,0.0,48.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,4101.0,350.0,18.5,1.0,0.0,0.0,4618.7,484.0,2161.4,326.0,7344.1,1074.0,0.0,0.0,0.0,0.0,56.0,7.0,0.0,0.0,0.00,0.0,0.0,0.0,3497.0,332.0,0.0,0.0,0.0,0.0,3710.7,438.0,1838.4,314.0,6094.3,994.0,0.0,0.0,0.0,0.0,40.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3801.0,370.0,0.0,0.0,0.0,0.0,6031.9,730.0,3906.2,680.0,10381.2,1638.0,0.0,0.0,80.0,8.0,0.0,0.0,0.00,0.0,0.0,0.0,7104.0,696.0,0.0,0.0,0.0,0.0,5742.6,677.0,3142.9,548.0,8543.9,1396.0,0.0,0.0,0.0,0.0,32.0,3.0,0.00,0.0,0.0,0.0,0.0,0.0,6268.0,640.0,0.0,0.0,0.0,0.0,7239.4,732.0,4044.9,688.0,11043.1,1755.0,0.0,0.0,0.0,0.0,120.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,5662.0,594.0,0.0,0.0

In [21]:
train_df.head(1)

,NOM BOUTIQUE,OPERATEUR,MACHINE,NOM DU PRODUIT,QUANTITE,VAT,PRIX TTC,TYPE,GAMME,MARQUE,FOURNISSEUR,ORDER ID (TICKET DE CAISSE),DATETIME,DATE_HEURE,MOIS_D_ANNEE,JOUR_DU_MOIS,JOUR_DE_SEMAINE,JOUR_D_ANNEE,SEMAINE_D_ANNEE,IS_WEEKEND,HEURE_DU_JOUR,HOTEL_NAME,HOTEL_CITY,HOTEL_LAT,HOTEL_LON,ALCOHOL_1_KM,ALCOHOL_2_KM,ALCOHOL_3_KM,BAKERY_1_KM,BAKERY_2_KM,BAKERY_3_KM,CONFECTIONERY_2_KM,CONFECTIONERY_3_KM,CONVENIENCE_1_KM,CONVENIENCE_2_KM,CONVENIENCE_3_KM,COSMETICS_2_KM,COSMETICS_3_KM,GIFT_2_KM,GIFT_3_KM,KIOSK_1_KM,KIOSK_2_KM,KIOSK_3_KM,SUPERMARKET_1_KM,SUPERMARKET_2_KM,SUPERMARKET_3_KM,TOBACCO_1_KM,TOBACCO_2_KM,TOBACCO_3_KM,BEVERAGES_1_KM,BEVERAGES_2_KM,BEVERAGES_3_KM,CONFECTIONERY_1_KM,COSMETICS_1_KM,GIFT_1_KM,GROCERY_2_KM,GROCERY_3_KM,GROCERY_1_KM,ICE_CREAM_2_KM,ICE_CREAM_3_KM,time,temp,dwpt,rhum,prcp,snow,wdir,wspd,wpgt,pres,tsun,coco,lat,lon,mois,annee,montant_vente
0,Ibis budget Nice,ADIPOS,SCANNER NICE,TONGS FEMME 100 NOIR,1,20.0,6.0,NON-F&B,ACCESSOIRES,DECATHLON,DECATHLON,9281,2023-08-10 12:04:22.555,2023-08-10 12:00:00,8,10,3,222,32,0,12,Ibis budget Nice,Nice,43.667571,7.214308,1,2,2,2,16,26,1.0,1.0,1,9,20,12.0,12.0,1,1,1.0,3.0,3.0,1.0,7,11,1.0,4.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-08-10 12:00:00,25.0,18.7,68.0,0.0,0.0,130.0,9.4,17.0,1018.7,55.0,2.0,43.667571,7.214308,8,2023,6.0

In [4]:
df_hotel_monthly.to_excel("transaction_prepared_data.xlsx", index = False)

In [52]:
train_df["HOTEL_NAME"].unique()

array(['Ibis budget Nice', 'Mercure Paris Montmartre Sacré-Cœur',
       'Novotel Megève Mont-Blanc', 'Novotel Paris Tour Eiffel',
       'Ibis budget Strasbourg Centre République'], dtype=object)